### PR TITLE
Bump sentry sdk constraint to 1.*

### PR DESCRIPTION
**Pull request by raethlo**
image

To be able to upgrade sentry to latest on other repos we need to upgrade sentry-sdk here as well. Not sure if there are any caveats.

### CODE REVIEW

**Comment by jerguslejko** [comment]
@raethlo did you check the change log? https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#0195

**Comment by raethlo** [comment]
there seem to be just two breaking changes:

in [0.20.0](https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#0200):
> BREAKING CHANGE: The default environment is now production, not based on release

and in [1.0.0](https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#100)
> BREAKING CHANGE: Feat: Moved auto_session_tracking experimental flag to a proper option and removed explicitly setting experimental session_mode in favor of auto detecting its value, hence enabling release health by default #994

ran a fulltext through both `parrot` and `parottools` and seems we don't use the deprecated flag - so we should be good to go.

**Review by jerguslejko — APPROVED** [review]

**Comment by vetyy** [comment]
@raethlo I upgraded sentry-sdk on parrottools https://github.com/parrot-com/parrottools/pull/8

**Comment by vetyy** [comment]
@raethlo you can upgrade parrottools to v0.1.5 too

**Comment by raethlo** [comment]
I mean, you could've commited to this branch but works 😂 - closing this one.

**Comment by raethlo** [comment]
I mean, you could've commited to this branch but works 😂 - closing this one.

**Pull request closed without merging**
